Nomenclature change
mm-project/qt_painter pull request #164
Opened 2019-12-06 11:42 UTC by levibyte

2019-12-09 07:33 UTC, nagaina requested changes

2019-12-09 07:33 UTC, nagaina commented on src/core/design.cpp
> +    m_is_saved = false;
alignment?

2019-12-09 07:33 UTC, nagaina commented on src/core/design.hpp
> +    bool isSaved() { return m_is_saved; }
consider using const, noexcept  where needed :P

2019-12-09 07:33 UTC, nagaina commented on src/core/iobject_pool.hpp
> +    virtual void dumpToFile(const std::string&) const override;
alignment

2019-12-09 20:56 UTC, levibyte commented on src/core/design.cpp
> +    m_is_saved = false;
done

2019-12-09 20:56 UTC, levibyte commented on src/core/iobject_pool.hpp
> +    virtual void dumpToFile(const std::string&) const override;
done

2019-12-09 20:56 UTC, levibyte commented on src/core/design.hpp
> +    bool isSaved() { return m_is_saved; }
done

2019-12-11 07:08 UTC, nagaina submitted a review, later dismissed

2019-12-11 07:08 UTC, nagaina commented on src/core/design.hpp
> +    bool isSaved() const noexcept { return m_is_saved; }
աբրիգոս ։Դ

2019-12-13 16:44 UTC, closed without merging